<a href="https://colab.research.google.com/github/SCJAforTS/Tareas-para-Temas-Selectos/blob/main/Tarea2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
rm -rf Tareas-para-Temas-Selectos

In [ ]:
!git clone https://github.com/SCJAforTS/Tareas-para-Temas-Selectos

Cloning into 'Tareas-para-Temas-Selectos'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 74 (delta 13), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (74/74), 2.52 MiB | 8.80 MiB/s, done.
Resolving deltas: 100% (13/13), done.

In [ ]:
!wget https://github.com/SCJAforTS/Tareas-para-Temas-Selectos/raw/refs/heads/main/cwurData%20-%20Repertory.csv
!wget https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20Times%20Data.csv
!wget https://github.com/SCJAforTS/Tareas-para-Temas-Selectos/raw/refs/heads/main/cwurData%20-%20Shangai%20Data.csv
!wget https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20cwurData.csv
!wget https://github.com/SCJAforTS/Tareas-para-Temas-Selectos/raw/refs/heads/main/cwurData%20-%20School%20and%20Country.csv

--2024-10-14 06:10:09--  https://github.com/SCJAforTS/Tareas-para-Temas-Selectos/raw/refs/heads/main/cwurData%20-%20Repertory.csv
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20Repertory.csv [following]
--2024-10-14 06:10:09--  https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20Repertory.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68886 (67K) [text/plain]
Saving to: ‘cwurData - Repertory.csv’

cwurData - Repertor 100%[===================>]  67.27K  --.-KB/s    in 0.07s

2024-10-14 06:10:10 (1014 KB/s) - ‘cwurData - Repertory.csv’ saved [68886/68886]

--2024-10-14 06:10:10--  https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20Times%20Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 234071 (229K) [text/plain]
Saving to: ‘cwurData - Times Data.csv’

cwurData - Times Da 100%[===================>] 228.58K  --.-KB/s    in 0.1s

2024-10-14 06:10:11 (2.02 MB/s) - ‘cwurData - Times Data.csv’ saved [234071/234071]

--2024-10-14 06:10:11--  https://github.com/SCJAforTS/Tareas-para-Temas-Selectos/raw/refs/heads/main/cwurData%20-%20Shangai%20Data.csv
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20Shangai%20Data.csv [following]
--2024-10-14 06:10:11--  https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20Shangai%20Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 121023 (118K) [text/plain]
Saving to: ‘cwurData - Shangai Data.csv’

cwurData - Shangai  100%[===================>] 118.19K  --.-KB/s    in 0.08s

2024-10-14 06:10:12 (1.49 MB/s) - ‘cwurData - Shangai Data.csv’ saved [121023/121023]

--2024-10-14 06:10:12--  https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20cwurData.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 177301 (173K) [text/plain]
Saving to: ‘cwurData - cwurData.csv’

cwurData - cwurData 100%[===================>] 173.15K  --.-KB/s    in 0.1s

2024-10-14 06:10:12 (1.66 MB/s) - ‘cwurData - cwurData.csv’ saved [177301/177301]

--2024-10-14 06:10:12--  https://github.com/SCJAforTS/Tareas-para-Temas-Selectos/raw/refs/heads/main/cwurData%20-%20School%20and%20Country.csv
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20School%20and%20Country.csv [following]
--2024-10-14 06:10:13--  https://raw.githubusercontent.com/SCJAforTS/Tareas-para-Temas-Selectos/refs/heads/main/cwurData%20-%20School%20and%20Country.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36232 (35K) [text/plain]
Saving to: ‘cwurData - School and Country.csv’

cwurData - School a 100%[===================>]  35.38K  --.-KB/s    in 0.03s

2024-10-14 06:10:13 (1.01 MB/s) - ‘cwurData - School and Country.csv’ saved [36232/36232]

In [ ]:
!cp 'cwurData - Repertory.csv' /content/drive/MyDrive/Tarea/
!cp 'cwurData - School and Country.csv' /content/drive/MyDrive/Tarea/
!cp 'cwurData - Shangai Data.csv' /content/drive/MyDrive/Tarea/
!cp 'cwurData - Times Data.csv' /content/drive/MyDrive/Tarea/
!cp 'cwurData - cwurData.csv' /content/drive/MyDrive/Tarea/

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import sqlite3

In [ ]:
ls -la

total 1180
drwxr-xr-x 1 root root   4096 Oct 14 06:10  ./
drwxr-xr-x 1 root root   4096 Oct 14 05:19  ../
drwxr-xr-x 4 root root   4096 Oct 10 13:27  .config/
-rw-r--r-- 1 root root 168016 Oct 14 05:23  cwurData.csv
-rw-r--r-- 1 root root 177301 Oct 14 06:10 'cwurData - cwurData.csv'
-rw-r--r-- 1 root root  68886 Oct 14 06:10 'cwurData - Repertory.csv'
-rw-r--r-- 1 root root  36232 Oct 14 06:10 'cwurData - School and Country.csv'
-rw-r--r-- 1 root root 121023 Oct 14 06:10 'cwurData - Shangai Data.csv'
-rw-r--r-- 1 root root 234071 Oct 14 06:10 'cwurData - Times Data.csv'
drwx------ 7 root root   4096 Oct 14 05:23  drive/
drwxr-xr-x 1 root root   4096 Oct 10 13:27  sample_data/
-rw-r--r-- 1 root root  32241 Oct 14 05:23  school_and_country_table.csv
-rw-r--r-- 1 root root 117558 Oct 14 05:23  shanghaiData.csv
drwxr-xr-x 3 root root   4096 Oct 14 06:07  Tareas-para-Temas-Selectos/
-rw-r--r-- 1 root root 212468 Oct 14 05:23  timesData.csv

In [ ]:
pwd

'/content'

In [ ]:
ls -la '/content/drive/My Drive/Tarea/cwurData - Repertory.csv'

-rw------- 1 root root 68886 Oct 14 06:10 '/content/drive/My Drive/Tarea/cwurData - Repertory.csv'

In [ ]:

# Connect to the database
conn = sqlite3.connect('Tarea.db')
c = conn.cursor()  # Create a cursor object

# Drop table if it exists - rep
c.execute("DROP TABLE IF EXISTS rep")


c.execute('''
    CREATE TABLE rep (
        id_school INTEGER PRIMARY KEY ,
        school_name TEXT
    )
''')


# Drop table if it exists - sc
c.execute("DROP TABLE IF EXISTS sc")

c.execute('''
    CREATE TABLE sc (
        id_school INTEGER PRIMARY KEY ,
        school_name TEXT,
        country TEXT
    )
''')

# Create table - td
c.execute("DROP TABLE IF EXISTS td")
c.execute('''
        CREATE TABLE td(
        id_school INTEGER,
        world_rank text,
        university_name TEXT,
        country TEXT,
        teaching FLOAT,
        research FLOAT,
        citations FLOAT,
        total_score FLOAT,
        num_students FLOAT,
        student_staff_ratio float,
        international_students FLOAT,
        year integer,
        FOREIGN KEY (id_school) REFERENCES rep(id_school)
    )
''')


c.execute("DROP TABLE IF EXISTS Shanghai")
c.execute('''
    CREATE TABLE Shanghai (
        id_school INTEGER,
        university_name TEXT,
        world_rank TEXT,
        national_rank INTEGER,
        alumni FLOAT,
        award FLOAT,
        hici FLOAT,
        ns FLOAT,
        year integer,
        FOREIGN KEY (id_school) REFERENCES rep(id_school)
    )
''')

# Create table - cw
c.execute("DROP TABLE IF EXISTS cw")
c.execute('''
    CREATE TABLE cw (
        id_school INTEGER,
        institution TEXT,
        world_rank TEXT,
        country TEXT,
        national_rank INTEGER,
        quality_of_education INTEGER,
        alumni_employment INTEGER,
        publications INTEGER,
        influence INTEGER,
        citations INTEGER,
        patents INTEGER,
        score FLOAT,
        year integer,
        FOREIGN KEY (id_school) REFERENCES rep(id_school)
    )
''')
# Create table -
c.execute("DROP TABLE IF EXISTS rankings")
c.execute('''
    CREATE TABLE rankings (
        id_school INTEGER,
        school_name TEXT,
        td_country TEXT,
        td_world_rank integer,
        shanghai_world_rank integer,
        cwur_world_rank integer,
        td_num_students FLOAT,
        td_international_students FLOAT,
        s_award FLOAT,
        cw_alumni_employment INTEGER,
        cw_publications INTEGER,
        cw_influence INTEGER,
        year integer,
        FOREIGN KEY (id_school) REFERENCES rep(id_school)
    )
''')
# Commit the changes
conn.commit()
conn.close()

In [ ]:
import pandas as pd
import os
import sqlite3

# Conectar a la base de datos
conn = sqlite3.connect('Tarea.db')

# Definir el directorio que contiene los archivos CSV
csv_dir = '/content/drive/My Drive/Tarea/'

# Diccionario que mapea archivos CSV a sus respectivas tablas
csv_to_table_mapping = {
    'cwurData - Repertory.csv': 'rep',
    'cwurData - School and Country.csv': 'sc',
    'cwurData - Shangai Data.csv': 'Shanghai',
    'cwurData - Times Data.csv': 'td',
    'cwurData - cwurData.csv': 'cw'
}

# Iterar a través de los archivos CSV e insertar datos en las tablas correspondientes
for csv_file, table_name in csv_to_table_mapping.items():
    # Definir la ruta completa al archivo CSV
    csv_file_path = os.path.join(csv_dir, csv_file)

    # Verificar si el archivo CSV existe
    if os.path.exists(csv_file_path):
        # Leer el archivo CSV en un DataFrame
        data_frame = pd.read_csv(csv_file_path)

        # Insertar el DataFrame en la tabla correspondiente
        data_frame.to_sql(table_name, conn, if_exists='append', index=False)
    else:
        print(f"File {csv_file} does not exist in the directory.")

# Confirmar los cambios y cerrar la conexión
conn.commit()
conn.close()

In [ ]:
%pwd

'/content'

In [ ]:


conn = sqlite3.connect('Tarea.db')
c = conn.cursor()

# Insert data into rankings
c.execute('''INSERT INTO  rankings(
        id_school,
        school_name ,
        td_country,
        td_world_rank,
        shanghai_world_rank ,
        cwur_world_rank ,
        td_num_students,
        td_international_students,
        s_award,
        cw_alumni_employment,
        cw_publications,
        cw_influence,
        year
)
SELECT DISTINCT
        rep.id_school,
        rep.school_name,
        td.country,
        CASE WHEN (LOWER(td.world_rank) = "none") THEN "Did not participate" ELSE td.world_rank END,
        CASE WHEN (LOWER(shanghai.world_rank) = "none") THEN "Did not participate" ELSE shanghai.world_rank END,
        CASE WHEN (LOWER(cw.world_rank) = "none") THEN "Did not participate" ELSE cw.world_rank END,
        td.num_students,
        td.international_students,
        shanghai.award,
        cw.alumni_employment,
        cw.publications,
        cw.influence,
        td.year
FROM
    rep
LEFT JOIN
    td ON td.id_school = rep.id_school
LEFT JOIN
    shanghai ON shanghai.id_school = rep.id_school
LEFT JOIN
    cw ON cw.id_school = rep.id_school
    ''')
# Commit the changes
conn.commit()
# Now, select the distinct records

c.execute('''
    SELECT  distinct*
    from rankings
     WHERE rankings.year = "2012"
''')

# Fetch the results
results = c.fetchall()

# Print the results
for row in results:
    print(row)

(1, 'Harvard University', 'United States of America', 2, 1, 1, '20,152', '25%', 100.0, 1, 1, 1, 2012)
(1, 'Harvard University', 'United States of America', 2, 1, 1, '20,152', '25%', 100.0, 9, 1, 1, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 11, '2,243', '27%', 67.2, 101, 38, 24, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 12, '2,243', '27%', 67.2, 303, 48, 6, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 12, '2,243', '27%', 67.2, 328, 53, 9, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 5, '2,243', '27%', 67.2, 29, 37, 22, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 11, '2,243', '27%', 68.8, 101, 38, 24, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 12, '2,243', '27%', 68.8, 303, 48, 6, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 12, '2,243', '27%', 68.8, 328, 53, 9, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 6, 5, '2,243', '27%', 68.8, 29, 37, 22, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 7, 11, '2,243', '27%', 66.7, 101, 38, 24, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 7, 12, '2,243', '27%', 66.7, 303, 48, 6, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 7, 12, '2,243', '27%', 66.7, 328, 53, 9, 2012)
(2, 'California Institute of Technology', 'United States of America', 1, 7, 5, '2,243', '27%', 66.7, 29, 37, 22, 2012)
(3, 'Massachusetts Institute of Technology', 'United States of America', 7, None, 2, '11,074', '33%', None, 17, 12, 4, 2012)
(3, 'Massachusetts Institute of Technology', 'United States of America', 7, None, 3, '11,074', '33%', None, 11, 15, 2, 2012)
(3, 'Massachusetts Institute of Technology', 'United States of America', 7, None, 4, '11,074', '33%', None, 16, 16, 3, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 78.4, 2, 5, 3, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 78.4, 2, 6, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 3, '15,596', '22%', 78.4, 11, 4, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 79.7, 2, 5, 3, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 79.7, 2, 6, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 3, '15,596', '22%', 79.7, 11, 4, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 80.7, 2, 5, 3, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 80.7, 2, 6, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 3, '15,596', '22%', 80.7, 11, 4, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 82.8, 2, 5, 3, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 82.8, 2, 6, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 3, '15,596', '22%', 82.8, 11, 4, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 89.6, 2, 5, 3, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 2, '15,596', '22%', 89.6, 2, 6, 2, 2012)
(4, 'Stanford University', 'United States of America', 2, 2, 3, '15,596', '22%', 89.6, 11, 4, 2, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 6, '7,929', '27%', 88.5, 14, 53, 33, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 8, '7,929', '27%', 88.5, 14, 58, 35, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 9, '7,929', '27%', 88.5, 15, 72, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 9, '7,929', '27%', 88.5, 16, 70, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 6, '7,929', '27%', 93.4, 14, 53, 33, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 8, '7,929', '27%', 93.4, 14, 58, 35, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 9, '7,929', '27%', 93.4, 15, 72, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 6, 9, '7,929', '27%', 93.4, 16, 70, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 6, '7,929', '27%', 87.1, 14, 53, 33, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 8, '7,929', '27%', 87.1, 14, 58, 35, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 9, '7,929', '27%', 87.1, 15, 72, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 9, '7,929', '27%', 87.1, 16, 70, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 6, '7,929', '27%', 89.2, 14, 53, 33, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 8, '7,929', '27%', 89.2, 14, 58, 35, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 9, '7,929', '27%', 89.2, 15, 72, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 9, '7,929', '27%', 89.2, 16, 70, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 6, '7,929', '27%', 91.3, 14, 53, 33, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 8, '7,929', '27%', 91.3, 14, 58, 35, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 9, '7,929', '27%', 91.3, 15, 72, 25, 2012)
(5, 'Princeton University', 'United States of America', 5, 7, 9, '7,929', '27%', 91.3, 16, 70, 25, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 96.6, 10, 10, 9, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 96.6, 10, 11, 6, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 96.6, 24, 16, 16, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 5, '18,812', '34%', 96.6, 15, 9, 11, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 96.7, 10, 10, 9, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 96.7, 10, 11, 6, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 96.7, 24, 16, 16, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 5, '18,812', '34%', 96.7, 15, 9, 11, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 97.2, 10, 10, 9, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 97.2, 10, 11, 6, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 97.2, 24, 16, 16, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 5, '18,812', '34%', 97.2, 15, 9, 11, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 97.3, 10, 10, 9, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 97.3, 10, 11, 6, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 4, '18,812', '34%', 97.3, 24, 16, 16, 2012)
(6, 'University of Cambridge', 'United Kingdom', 6, 5, 5, '18,812', '34%', 97.3, 15, 9, 11, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 3, '19,919', '34%', 54.9, 12, 11, 7, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 54.9, 12, 11, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 54.9, 13, 7, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 7, '19,919', '34%', 54.9, 28, 15, 13, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 3, '19,919', '34%', 55.3, 12, 11, 7, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 55.3, 12, 11, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 55.3, 13, 7, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 7, '19,919', '34%', 55.3, 28, 15, 13, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 3, '19,919', '34%', 56.6, 12, 11, 7, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 56.6, 12, 11, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 56.6, 13, 7, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 7, '19,919', '34%', 56.6, 28, 15, 13, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 3, '19,919', '34%', 57.6, 12, 11, 7, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 57.6, 12, 11, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 5, '19,919', '34%', 57.6, 13, 7, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 10, 7, '19,919', '34%', 57.6, 28, 15, 13, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 9, 3, '19,919', '34%', 54.9, 12, 11, 7, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 9, 5, '19,919', '34%', 54.9, 12, 11, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 9, 5, '19,919', '34%', 54.9, 13, 7, 12, 2012)
(7, 'University of Oxford', 'United Kingdom', 4, 9, 7, '19,919', '34%', 54.9, 28, 15, 13, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 3, 10, '36,186', '15%', 79.0, 52, 6, 5, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 3, 7, '36,186', '15%', 79.0, 21, 10, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 3, 7, '36,186', '15%', 79.0, 22, 7, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 3, 7, '36,186', '15%', 79.0, 28, 8, 6, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 10, '36,186', '15%', 79.3, 52, 6, 5, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 79.3, 21, 10, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 79.3, 22, 7, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 79.3, 28, 8, 6, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 10, '36,186', '15%', 79.4, 52, 6, 5, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 79.4, 21, 10, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 79.4, 22, 7, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 79.4, 28, 8, 6, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 10, '36,186', '15%', 80.9, 52, 6, 5, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 80.9, 21, 10, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 80.9, 22, 7, 4, 2012)
(8, 'University of California, Berkeley', 'United States of America', 10, 4, 7, '36,186', '15%', 80.9, 28, 8, 6, 2012)
(9, 'Imperial College London', 'United Kingdom', 8, None, 27, '15,060', '51%', None, 92, 17, 22, 2012)
(9, 'Imperial College London', 'United Kingdom', 8, None, 28, '15,060', '51%', None, 73, 26, 26, 2012)
(9, 'Imperial College London', 'United Kingdom', 8, None, 35, '15,060', '51%', None, 82, 19, 26, 2012)
(9, 'Imperial College London', 'United Kingdom', 8, None, 39, '15,060', '51%', None, 98, 20, 27, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 44.5, 25, 18, 7, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 44.5, 25, 20, 12, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 11, '11,751', '20%', 44.5, 26, 18, 8, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 8, '11,751', '20%', 44.5, 31, 14, 6, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 44.9, 25, 18, 7, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 44.9, 25, 20, 12, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 11, '11,751', '20%', 44.9, 26, 18, 8, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 8, '11,751', '20%', 44.9, 31, 14, 6, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 45.5, 25, 18, 7, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 45.5, 25, 20, 12, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 11, '11,751', '20%', 45.5, 26, 18, 8, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 8, '11,751', '20%', 45.5, 31, 14, 6, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 50.4, 25, 18, 7, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 10, '11,751', '20%', 50.4, 25, 20, 12, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 11, '11,751', '20%', 50.4, 26, 18, 8, 2012)
(10, 'Yale University', 'United States of America', 11, 11, 8, '11,751', '20%', 50.4, 31, 14, 6, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 15, '38,206', '15%', 42.6, 27, 6, 14, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 16, '38,206', '15%', 42.6, 35, 5, 15, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 19, '38,206', '15%', 42.6, 59, 3, 11, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 15, '38,206', '15%', 43.4, 27, 6, 14, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 16, '38,206', '15%', 43.4, 35, 5, 15, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 19, '38,206', '15%', 43.4, 59, 3, 11, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 15, '38,206', '15%', 47.1, 27, 6, 14, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 16, '38,206', '15%', 47.1, 35, 5, 15, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 19, '38,206', '15%', 47.1, 59, 3, 11, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 15, '38,206', '15%', 47.4, 27, 6, 14, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 16, '38,206', '15%', 47.4, 35, 5, 15, 2012)
(11, 'University of California, Los Angeles', 'United States of America', 13, 12, 19, '38,206', '15%', 47.4, 59, 3, 11, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 11, '14,221', '21%', 83.4, 26, 34, 20, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 83.4, 14, 17, 16, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 83.4, 14, 17, 19, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 9, '14,221', '21%', 83.4, 19, 37, 21, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 11, '14,221', '21%', 83.9, 26, 34, 20, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 83.9, 14, 17, 16, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 83.9, 14, 17, 19, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 9, '14,221', '21%', 83.9, 19, 37, 21, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 11, '14,221', '21%', 85.3, 26, 34, 20, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 85.3, 14, 17, 16, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 85.3, 14, 17, 19, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 9, '14,221', '21%', 85.3, 19, 37, 21, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 11, '14,221', '21%', 86.3, 26, 34, 20, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 86.3, 14, 17, 16, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 8, '14,221', '21%', 86.3, 14, 17, 19, 2012)
(12, 'University of Chicago', 'United States of America', 9, 9, 9, '14,221', '21%', 86.3, 19, 37, 21, 2012)
(13, 'Johns Hopkins University', 'United States of America', 14, 16, 15, '15,128', '23%', 33.6, 77, 11, 9, 2012)
(13, 'Johns Hopkins University', 'United States of America', 14, 16, 16, '15,128', '23%', 33.6, 84, 4, 11, 2012)
(13, 'Johns Hopkins University', 'United States of America', 14, 16, 17, '15,128', '23%', 33.6, 96, 4, 5, 2012)
(13, 'Johns Hopkins University', 'United States of America', 14, 16, 19, '15,128', '23%', 33.6, 75, 4, 10, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 10, '21,424', '19%', 49.8, 18, 24, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 11, '21,424', '19%', 49.8, 18, 23, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 12, '21,424', '19%', 49.8, 42, 22, 21, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 13, '21,424', '19%', 49.8, 23, 21, 19, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 10, '21,424', '19%', 50.2, 18, 24, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 11, '21,424', '19%', 50.2, 18, 23, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 12, '21,424', '19%', 50.2, 42, 22, 21, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 13, '21,424', '19%', 50.2, 23, 21, 19, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 10, '21,424', '19%', 51.1, 18, 24, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 11, '21,424', '19%', 51.1, 18, 23, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 12, '21,424', '19%', 51.1, 42, 22, 21, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 13, '21,424', '19%', 51.1, 23, 21, 19, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 10, '21,424', '19%', 51.3, 18, 24, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 11, '21,424', '19%', 51.3, 18, 23, 15, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 12, '21,424', '19%', 51.3, 42, 22, 21, 2012)
(14, 'Cornell University', 'United States of America', 20, 13, 13, '21,424', '19%', 51.3, 23, 21, 19, 2012)
(15, 'ETH Zurich – Swiss Federal Institute of Technology Zurich', 'Switzerland', 15, None, None, '18,178', '37%', None, None, None, None, 2012)
(16, 'University of Michigan', 'United States of America', 18, None, None, '41,786', '16%', None, None, None, None, 2012)
(17, 'University of Toronto', 'Canada', 19, 24, 29, '66,198', '15%', 17.2, 81, 2, 13, 2012)
(17, 'University of Toronto', 'Canada', 19, 24, 31, '66,198', '15%', 17.2, 45, 2, 18, 2012)
(17, 'University of Toronto', 'Canada', 19, 24, 32, '66,198', '15%', 17.2, 51, 2, 17, 2012)
(17, 'University of Toronto', 'Canada', 19, 24, 35, '66,198', '15%', 17.2, 101, 7, 14, 2012)
(17, 'University of Toronto', 'Canada', 19, 25, 29, '66,198', '15%', 17.2, 81, 2, 13, 2012)
(17, 'University of Toronto', 'Canada', 19, 25, 31, '66,198', '15%', 17.2, 45, 2, 18, 2012)
(17, 'University of Toronto', 'Canada', 19, 25, 32, '66,198', '15%', 17.2, 51, 2, 17, 2012)
(17, 'University of Toronto', 'Canada', 19, 25, 35, '66,198', '15%', 17.2, 101, 7, 14, 2012)
(17, 'University of Toronto', 'Canada', 19, 26, 29, '66,198', '15%', 19.2, 81, 2, 13, 2012)
(17, 'University of Toronto', 'Canada', 19, 26, 31, '66,198', '15%', 19.2, 45, 2, 18, 2012)
(17, 'University of Toronto', 'Canada', 19, 26, 32, '66,198', '15%', 19.2, 51, 2, 17, 2012)
(17, 'University of Toronto', 'Canada', 19, 26, 35, '66,198', '15%', 19.2, 101, 7, 14, 2012)

In [ ]:
#Show the structure

# Connect to your SQLite database
conn = sqlite3.connect('Tarea.db')
c = conn.cursor()

table_name = 'rankings'

# Execute the PRAGMA command to get table structure
c.execute(f"PRAGMA table_info({table_name});")

# Fetch the results
structure = c.fetchall()

# Display the table structure
print(f"Structure of table '{table_name}':")
for column in structure:
    print(f"Column Name: {column[1]}, Data Type: {column[2]}, Not Null: {column[3]}, Default Value: {column[4]}")

Structure of table 'rankings':
Column Name: id_school, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: school_name, Data Type: TEXT, Not Null: 0, Default Value: None
Column Name: td_country, Data Type: TEXT, Not Null: 0, Default Value: None
Column Name: td_world_rank, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: shanghai_world_rank, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: cwur_world_rank, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: td_num_students, Data Type: FLOAT, Not Null: 0, Default Value: None
Column Name: td_international_students, Data Type: FLOAT, Not Null: 0, Default Value: None
Column Name: s_award, Data Type: FLOAT, Not Null: 0, Default Value: None
Column Name: cw_alumni_employment, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: cw_publications, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: cw_influence, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: year, Data Type: INTEGER, Not Null: 0, Default Value: None

Consultas

In [ ]:
# Universidades que más veces han estado en el ranking


# Connect to the SQLite database
conn = sqlite3.connect('Tarea.db')
c = conn.cursor()

try:
    # Execute the query to count universities
    c.execute('''
        SELECT
            td.university_name,
            COUNT(td.id_school) AS school_count
        FROM
            td
        GROUP BY
            td.university_name
        ORDER BY
            school_count DESC
    ''')

    # Fetch the results
    results = c.fetchall()

    # Check if results were returned
    if results:
        # Print the results
        print("Universities and their counts:")
        for row in results:
            print(f"University: {row[0]}, Count: {row[1]}")
    else:
        print("No results found.")

except sqlite3.Error as e:
    print(f"An error occurred: {e}")

Universities and their counts:
University: École Polytechnique Fédérale de Lausanne, Count: 6
University: École Polytechnique, Count: 6
University: École Normale Supérieure de Lyon, Count: 6
University: École Normale Supérieure, Count: 6
University: Zhejiang University, Count: 6
University: Yonsei University, Count: 6
University: Yeshiva University, Count: 6
University: Yale University, Count: 6
University: William & Mary, Count: 6
University: Washington University in St Louis, Count: 6
University: Wake Forest University, Count: 6
University: Wageningen University and Research Center, Count: 6
University: Vanderbilt University, Count: 6
University: VU University Amsterdam, Count: 6
University: Utrecht University, Count: 6
University: Uppsala University, Count: 6
University: University of Zurich, Count: 6
University: University of York, Count: 6
University: University of Würzburg, Count: 6
University: University of Washington, Count: 6
University: University of Virginia, Count: 6
University: University of Vienna, Count: 6
University: University of Victoria, Count: 6
University: University of Utah, Count: 6
University: University of Tübingen, Count: 6
University: University of Twente, Count: 6
University: University of Toronto, Count: 6
University: University of Tokyo, Count: 6
University: University of Sydney, Count: 6
University: University of Sussex, Count: 6
University: University of St Andrews, Count: 6
University: University of Southern California, Count: 6
University: University of Southampton, Count: 6
University: University of Sheffield, Count: 6
University: University of Science and Technology of China, Count: 6
University: University of Pittsburgh, Count: 6
University: University of Pennsylvania, Count: 6
University: University of Oxford, Count: 6
University: University of Nottingham, Count: 6
University: University of Notre Dame, Count: 6
University: University of North Carolina at Chapel Hill, Count: 6
University: University of New South Wales, Count: 6
University: University of Montreal, Count: 6
University: University of Minnesota, Count: 6
University: University of Michigan, Count: 6
University: University of Melbourne, Count: 6
University: University of Massachusetts, Count: 6
University: University of Maryland, College Park, Count: 6
University: University of Manchester, Count: 6
University: University of Liverpool, Count: 6
University: University of Leeds, Count: 6
University: University of Lausanne, Count: 6
University: University of Konstanz, Count: 6
University: University of Iowa, Count: 6
University: University of Innsbruck, Count: 6
University: University of Illinois at Urbana-Champaign, Count: 6
University: University of Illinois at Chicago, Count: 6
University: University of Hong Kong, Count: 6
University: University of Helsinki, Count: 6
University: University of Göttingen, Count: 6
University: University of Groningen, Count: 6
University: University of Glasgow, Count: 6
University: University of Geneva, Count: 6
University: University of Freiburg, Count: 6
University: University of Exeter, Count: 6
University: University of Edinburgh, Count: 6
University: University of East Anglia, Count: 6
University: University of Dundee, Count: 6
University: University of Delaware, Count: 6
University: University of Copenhagen, Count: 6
University: University of Colorado Boulder, Count: 6
University: University of Cincinnati, Count: 6
University: University of Chicago, Count: 6
University: University of Cape Town, Count: 6
University: University of Cambridge, Count: 6
University: University of California, Santa Cruz, Count: 6
University: University of California, Santa Barbara, Count: 6
University: University of California, San Diego, Count: 6
University: University of California, Riverside, Count: 6
University: University of California, Los Angeles, Count: 6
University: University of California, Irvine, Count: 6
University: University of California, Davis, Count: 6
University: University of California, Berkeley, Count: 6
University: University of British Columbia, Count: 6
University: University of Bristol, Count: 6
University: University of Birmingham, Count: 6
University: University of Bergen, Count: 6
University: University of Basel, Count: 6
University: University of Barcelona, Count: 6
University: University of Auckland, Count: 6
University: University of Arizona, Count: 6
University: University of Amsterdam, Count: 6
University: University of Alberta, Count: 6
University: University of Adelaide, Count: 6
University: University of Aberdeen, Count: 6
University: University College London, Count: 6
University: University College Dublin, Count: 6
University: Tufts University, Count: 6
University: Tsinghua University, Count: 6
University: Trinity College Dublin, Count: 6
University: Tokyo Institute of Technology, Count: 6
University: Tohoku University, Count: 6
University: The University of Queensland, Count: 6
University: Technical University of Munich, Count: 6
University: Technical University of Denmark, Count: 6
University: Swedish University of Agricultural Sciences, Count: 6
University: Sun Yat-sen University, Count: 6
University: Stony Brook University, Count: 6
University: Stockholm University, Count: 6
University: Stanford University, Count: 6
University: Simon Fraser University, Count: 6
University: Seoul National University, Count: 6
University: Rutgers, the State University of New Jersey, Count: 6
University: Royal Holloway, University of London, Count: 6
University: Rice University, Count: 6
University: Rensselaer Polytechnic Institute, Count: 6
University: RWTH Aachen University, Count: 6
University: Queen Mary University of London, Count: 6
University: Purdue University, Count: 6
University: Princeton University, Count: 6
University: Pompeu Fabra University, Count: 6
University: Pohang University of Science and Technology, Count: 6
University: Pierre and Marie Curie University, Count: 6
University: Pennsylvania State University, Count: 6
University: Peking University, Count: 6
University: Osaka University, Count: 6
University: Ohio State University, Count: 6
University: Northwestern University, Count: 6
University: Newcastle University, Count: 6
University: New York University, Count: 6
University: National University of Singapore, Count: 6
University: National Tsing Hua University, Count: 6
University: National Taiwan University, Count: 6
University: National Sun Yat-Sen University, Count: 6
University: National Chiao Tung University, Count: 6
University: Nanyang Technological University, Count: 6
University: Nanjing University, Count: 6
University: Monash University, Count: 6
University: Middle East Technical University, Count: 6
University: Michigan State University, Count: 6
University: McMaster University, Count: 6
University: McGill University, Count: 6
University: Massachusetts Institute of Technology, Count: 6
University: Lund University, Count: 6
University: London School of Economics and Political Science, Count: 6
University: Leiden University, Count: 6
University: Lancaster University, Count: 6
University: LMU Munich, Count: 6
University: Kyoto University, Count: 6
University: Korea Advanced Institute of Science and Technology (KAIST), Count: 6
University: King’s College London, Count: 6
University: Karolinska Institute, Count: 6
University: Karlsruhe Institute of Technology, Count: 6
University: KU Leuven, Count: 6
University: KTH Royal Institute of Technology, Count: 6
University: Johns Hopkins University, Count: 6
University: Iowa State University, Count: 6
University: Indiana University, Count: 6
University: Imperial College London, Count: 6
University: Humboldt University of Berlin, Count: 6
University: Hong Kong University of Science and Technology, Count: 6
University: Hong Kong Polytechnic University, Count: 6
University: Hong Kong Baptist University, Count: 6
University: Heidelberg University, Count: 6
University: Harvard University, Count: 6
University: Goethe University Frankfurt, Count: 6
University: Ghent University, Count: 6
University: Georgia Institute of Technology, Count: 6
University: Georgetown University, Count: 6
University: George Washington University, Count: 6
University: Erasmus University Rotterdam, Count: 6
University: Emory University, Count: 6
University: Eindhoven University of Technology, Count: 6
University: ETH Zurich – Swiss Federal Institute of Technology Zurich, Count: 6
University: Durham University, Count: 6
University: Duke University, Count: 6
University: Drexel University, Count: 6
University: Delft University of Technology, Count: 6
University: Dartmouth College, Count: 6
University: Dalhousie University, Count: 6
University: Cornell University, Count: 6
University: Columbia University, Count: 6
University: Case Western Reserve University, Count: 6
University: Carnegie Mellon University, Count: 6
University: California Institute of Technology, Count: 6
University: Brown University, Count: 6
University: Boston University, Count: 6
University: Boston College, Count: 6
University: Birkbeck, University of London, Count: 6
University: Bilkent University, Count: 6
University: Bielefeld University, Count: 6
University: Australian National University, Count: 6
University: Arizona State University, Count: 6
University: Aarhus University, Count: 6
University: York University, Count: 5
University: Wayne State University, Count: 5
University: Washington State University, Count: 5
University: Vrije Universiteit Brussel, Count: 5
University: Virginia Polytechnic Institute and State University, Count: 5
University: Vienna University of Technology, Count: 5
University: Victoria University of Wellington, Count: 5
University: Université Libre de Bruxelles, Count: 5
University: Université Catholique de Louvain, Count: 5
University: University of the Witwatersrand, Count: 5
University: University of Wollongong, Count: 5
University: University of Wisconsin-Madison, Count: 5
University: University of Western Ontario, Count: 5
University: University of Western Australia, Count: 5
University: University of Waterloo, Count: 5
University: University of Warwick, Count: 5
University: University of Warsaw, Count: 5
University: University of Waikato, Count: 5
University: University of Valencia, Count: 5
University: University of Tsukuba, Count: 5
University: University of Trieste, Count: 5
University: University of Trento, Count: 5
University: University of Texas at Dallas, Count: 5
University: University of Texas at Austin, Count: 5
University: University of Tampere, Count: 5
University: University of São Paulo, Count: 5
University: University of Strasbourg, Count: 5
University: University of Stirling, Count: 5
University: University of Southern Denmark, Count: 5
University: University of South Florida, Count: 5
University: University of South Carolina, Count: 5
University: University of South Australia, Count: 5
University: University of Salento, Count: 5
University: University of Rochester, Count: 5
University: University of Reading, Count: 5
University: University of Pisa, Count: 5
University: University of Padua, Count: 5
University: University of Ottawa, Count: 5
University: University of Otago, Count: 5
University: University of Oslo, Count: 5
University: University of Newcastle, Count: 5
University: University of Münster, Count: 5
University: University of Missouri, Count: 5
University: University of Milan-Bicocca, Count: 5
University: University of Milan, Count: 5
University: University of Miami, Count: 5
University: University of Manitoba, Count: 5
University: University of Liège, Count: 5
University: University of Leicester, Count: 5
University: University of Kiel, Count: 5
University: University of Iceland, Count: 5
University: University of Houston, Count: 5
University: University of Hertfordshire, Count: 5
University: University of Graz, Count: 5
University: University of Gothenburg, Count: 5
University: University of Georgia, Count: 5
University: University of Florida, Count: 5
University: University of Ferrara, Count: 5
University: University of Essex, Count: 5
University: University of Eastern Finland, Count: 5
University: University of Crete, Count: 5
University: University of Canterbury, Count: 5
University: University of Calgary, Count: 5
University: University of Bonn, Count: 5
University: University of Bologna, Count: 5
University: University of Bern, Count: 5
University: University of Bath, Count: 5
University: University of Antwerp, Count: 5
University: University at Buffalo, Count: 5
University: University College Cork, Count: 5
University: Umeå University, Count: 5
University: UiT The Arctic University of Norway, Count: 5
University: Tulane University, Count: 5
University: Tokyo Metropolitan University, Count: 5
University: Tokyo Medical and Dental University (TMDU), Count: 5
University: Tilburg University, Count: 5
University: Texas A&M University, Count: 5
University: Tel Aviv University, Count: 5
University: Technion Israel Institute of Technology, Count: 5
University: Technical University of Darmstadt, Count: 5
University: TU Dresden, Count: 5
University: Sungkyunkwan University (SKKU), Count: 5
University: Stellenbosch University, Count: 5
University: State University of New York Albany, Count: 5
University: State University of Campinas, Count: 5
University: Sharif University of Technology, Count: 5
University: Shanghai Jiao Tong University, Count: 5
University: Sapienza University of Rome, Count: 5
University: Ruhr University Bochum, Count: 5
University: Radboud University Nijmegen, Count: 5
University: Queen’s University Belfast, Count: 5
University: Queen’s University, Count: 5
University: Queensland University of Technology, Count: 5
University: Polytechnic University of Milan, Count: 5
University: Paris Diderot University – Paris 7, Count: 5
University: Norwegian University of Science and Technology, Count: 5
University: Northeastern University, Count: 5
University: National University of Ireland, Galway, Count: 5
University: National Taiwan University of Science and Technology (Taiwan Tech), Count: 5
University: Nagoya University, Count: 5
University: Montpellier University, Count: 5
University: Macquarie University, Count: 5
University: Maastricht University, Count: 5
University: Lomonosov Moscow State University, Count: 5
University: Linköping University, Count: 5
University: Lehigh University, Count: 5
University: Kyushu University, Count: 5
University: Korea University, Count: 5
University: Istanbul Technical University, Count: 5
University: Hokkaido University, Count: 5
University: Hebrew University of Jerusalem, Count: 5
University: George Mason University, Count: 5
University: Fudan University, Count: 5
University: Free University of Berlin, Count: 5
University: Deakin University, Count: 5
University: Colorado State University, Count: 5
University: Colorado School of Mines, Count: 5
University: City University of Hong Kong, Count: 5
University: Chinese University of Hong Kong, Count: 5
University: Charles University in Prague, Count: 5
University: Charles Darwin University, Count: 5
University: Chalmers University of Technology, Count: 5
University: Carleton University, Count: 5
University: Cardiff University, Count: 5
University: Brunel University London, Count: 5
University: Brandeis University, Count: 5
University: Boğaziçi University, Count: 5
University: Bangor University, Count: 5
University: Autonomous University of Madrid, Count: 5
University: Autonomous University of Barcelona, Count: 5
University: Aberystwyth University, Count: 5
University: Aalto University, Count: 5
University: Aalborg University, Count: 5
University: Waseda University, Count: 4
University: University of the Andes, Colombia, Count: 4
University: University of Turin, Count: 4
University: University of Technology Sydney, Count: 4
University: University of Tasmania, Count: 4
University: University of Tartu, Count: 4
University: University of Surrey, Count: 4
University: University of Portsmouth, Count: 4
University: University of Porto, Count: 4
University: University of Pavia, Count: 4
University: University of Oklahoma, Count: 4
University: University of Montana, Count: 4
University: University of Minho, Count: 4
University: University of Maryland, Baltimore County, Count: 4
University: University of Kansas, Count: 4
University: University of Jyväskylä, Count: 4
University: University of Hawai’i at Mānoa, Count: 4
University: University of Guelph, Count: 4
University: University of Fribourg, Count: 4
University: University of Erlangen-Nuremberg, Count: 4
University: University of Duisburg-Essen, Count: 4
University: University of Connecticut, Count: 4
University: University of Bari Aldo Moro, Count: 4
University: Ulm University, Count: 4
University: Swinburne University of Technology, Count: 4
University: St George’s, University of London, Count: 4
University: Renmin University of China, Count: 4
University: Polytechnic University of Valencia, Count: 4
University: Plymouth University, Count: 4
University: Paris-Sud University, Count: 4
University: Oregon State University, Count: 4
University: National University of Ireland, Maynooth, Count: 4
University: National Cheng Kung University, Count: 4
University: National Central University, Count: 4
University: Murdoch University, Count: 4
University: Medical University of Vienna, Count: 4
University: Loughborough University, Count: 4
University: Leibniz University of Hanover, Count: 4
University: Laval University, Count: 4
University: Koç University, Count: 4
University: King Mongkut’s University of Technology Thonburi, Count: 4
University: Keele University, Count: 4
University: Kansas State University, Count: 4
University: Joseph Fourier University, Count: 4
University: Johannes Kepler University of Linz, Count: 4
University: Indian Institute of Technology Roorkee, Count: 4
University: Indian Institute of Technology Bombay, Count: 4
University: Heriot-Watt University, Count: 4
University: Georgia Health Sciences University, Count: 4
University: Florida Institute of Technology, Count: 4
University: Creighton University, Count: 4
University: Claude Bernard University Lyon 1, Count: 4
University: Bayreuth University, Count: 4
University: Wuhan University, Count: 3
University: University of Wyoming, Count: 3
University: University of Vigo, Count: 3
University: University of Vermont, Count: 3
University: University of Turku, Count: 3
University: University of Texas at San Antonio, Count: 3
University: University of Strathclyde, Count: 3
University: University of Nebraska-Lincoln, Count: 3
University: University of Navarra, Count: 3
University: University of Modena and Reggio Emilia, Count: 3
University: University of Florence, Count: 3
University: University of Cologne, Count: 3
University: University of Aveiro, Count: 3
University: Temple University, Count: 3
University: San Diego State University, Count: 3
University: Panjab University, Count: 3
University: Mines ParisTech, Count: 3
University: Massey University, Count: 3
University: Liverpool John Moores University, Count: 3
University: King Abdulaziz University, Count: 3
University: Kent State University, Count: 3
University: Keio University, Count: 3
University: Jagiellonian University, Count: 3
University: Indian Institute of Technology Kharagpur, Count: 3
University: Hanyang University, Count: 3
University: Flinders University, Count: 3
University: Curtin University, Count: 3
University: Binghamton University, State University of New York, Count: 3
University: Aston University, Count: 3
University: Alexandria University, Count: 3
University: Yuan Ze University, Count: 2
University: Wuhan University of Technology, Count: 2
University: Western Sydney University, Count: 2
University: University of Zaragoza, Count: 2
University: University of Stuttgart, Count: 2
University: University of Seoul, Count: 2
University: University of Rovira i Virgili, Count: 2
University: University of Rome III, Count: 2

In [ ]:


# Connect to the SQLite database
conn = sqlite3.connect('Tarea.db')
c = conn.cursor()

c.execute('''
  SELECT COUNT(*) FROM rankings;'''
)
row_count = c.fetchone()[0]
print(f"Number of rows in rankings table: {row_count}")

Number of rows in rankings table: 13674

In [ ]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('Tarea.db')
c = conn.cursor()

try:
    c.execute('''
    WITH top_ten AS (
        SELECT DISTINCT
            rk.id_school,
            rk.school_name,
            CASE WHEN LOWER(rk.td_world_rank) < '10' THEN 1 ELSE 0 END AS td_top_ten,
            CASE WHEN LOWER(rk.shanghai_world_rank) < '10' THEN 1 ELSE 0 END AS sh_top_ten,
            CASE WHEN LOWER(rk.cwur_world_rank) < '10' THEN 1 ELSE 0 END AS cwur_top_ten,
            rk.year
        FROM rankings rk
        WHERE rk.year >= 2012
    ),

    bq AS (
        SELECT DISTINCT
            id_school,
            school_name,
            SUM(td_top_ten) AS td_top_ten_times,
            SUM(sh_top_ten) AS sh_top_ten_times,
            SUM(cwur_top_ten) AS cwur_top_ten_times,
            year
        FROM top_ten
        GROUP BY id_school, school_name
    )

    SELECT DISTINCT
        id_school,
        school_name,
        td_top_ten_times,
        sh_top_ten_times,
        cwur_top_ten_times,
        CASE
            WHEN (td_top_ten_times > sh_top_ten_times AND td_top_ten_times > cwur_top_ten_times) THEN 'stands out in Times Data'
            WHEN (sh_top_ten_times > td_top_ten_times AND sh_top_ten_times > cwur_top_ten_times) THEN 'stands out in Shanghai'
            WHEN (cwur_top_ten_times > td_top_ten_times AND cwur_top_ten_times > sh_top_ten_times) THEN 'stands out in CWUR'
            ELSE 'Draw'
        END AS Best_qualifier
    FROM bq
    WHERE year >= 2012
    ORDER BY id_school ASC;
    ''')

    # Fetch the results
    res = c.fetchall()

    # Check if results were returned
    if res:
        # Print the results
        print("University Rankings:")
        print("ID, School Name, TD Top Ten Times, Shanghai Top Ten Times, CWUR Top Ten Times, Best Qualifier")
        for row in res:
            print(row)
    else:
        print("No results found.")

except sqlite3.Error as e:
    print(f"An error occurred: {e}")

University Rankings:
ID, School Name, TD Top Ten Times, Shanghai Top Ten Times, CWUR Top Ten Times, Best Qualifier
(1, 'Harvard University', 0, 5, 5, 'Draw')
(2, 'California Institute of Technology', 5, 0, 0, 'stands out in Times Data')
(3, 'Massachusetts Institute of Technology', 0, 0, 0, 'Draw')
(4, 'Stanford University', 0, 0, 0, 'Draw')
(5, 'Princeton University', 0, 0, 0, 'Draw')
(6, 'University of Cambridge', 0, 0, 0, 'Draw')
(7, 'University of Oxford', 0, 0, 0, 'Draw')
(8, 'University of California, Berkeley', 0, 0, 0, 'Draw')
(9, 'Imperial College London', 0, 0, 0, 'Draw')
(10, 'Yale University', 0, 0, 0, 'Draw')
(11, 'University of California, Los Angeles', 0, 0, 0, 'Draw')
(12, 'University of Chicago', 0, 0, 0, 'Draw')
(13, 'Johns Hopkins University', 0, 0, 0, 'Draw')
(14, 'Cornell University', 0, 0, 0, 'Draw')
(15, 'ETH Zurich – Swiss Federal Institute of Technology Zurich', 0, 0, 0, 'Draw')
(16, 'University of Michigan', 0, 0, 0, 'Draw')
(17, 'University of Toronto', 0, 0, 0, 'Draw')
(18, 'Columbia University', 0, 0, 0, 'Draw')
(19, 'University of Pennsylvania', 0, 0, 0, 'Draw')
(20, 'Carnegie Mellon University', 0, 0, 0, 'Draw')
(21, 'University of Hong Kong', 0, 0, 0, 'Draw')
(22, 'University College London', 0, 0, 0, 'Draw')
(23, 'University of Washington', 0, 0, 0, 'Draw')
(24, 'Duke University', 0, 0, 0, 'Draw')
(25, 'Northwestern University', 0, 0, 0, 'Draw')
(26, 'University of Tokyo', 0, 0, 0, 'Draw')
(27, 'Georgia Institute of Technology', 0, 0, 0, 'Draw')
(28, 'Pohang University of Science and Technology', 0, 0, 0, 'Draw')
(29, 'University of California, Santa Barbara', 0, 0, 0, 'Draw')
(30, 'University of British Columbia', 0, 0, 0, 'Draw')
(31, 'University of North Carolina at Chapel Hill', 0, 0, 0, 'Draw')
(32, 'University of California, San Diego', 0, 0, 0, 'Draw')
(33, 'University of Illinois at Urbana-Champaign', 0, 0, 0, 'Draw')
(34, 'National University of Singapore', 0, 0, 0, 'Draw')
(35, 'McGill University', 0, 0, 0, 'Draw')
(36, 'University of Melbourne', 0, 0, 0, 'Draw')
(37, 'Peking University', 0, 0, 0, 'Draw')
(38, 'Washington University in St Louis', 0, 0, 0, 'Draw')
(39, 'École Polytechnique', 0, 0, 0, 'Draw')
(40, 'University of Edinburgh', 0, 0, 0, 'Draw')
(41, 'Hong Kong University of Science and Technology', 0, 0, 0, 'Draw')
(42, 'École Normale Supérieure', 0, 0, 0, 'Draw')
(43, 'Australian National University', 0, 0, 0, 'Draw')
(44, 'Karolinska Institute', 0, 0, 0, 'Draw')
(45, 'University of Göttingen', 0, 0, 0, 'Draw')
(47, 'Rice University', 0, 0, 0, 'Draw')
(48, 'École Polytechnique Fédérale de Lausanne', 0, 0, 0, 'Draw')
(49, 'University of California, Irvine', 0, 0, 0, 'Draw')
(50, 'University of Science and Technology of China', 0, 0, 0, 'Draw')
(51, 'Vanderbilt University', 0, 0, 0, 'Draw')
(52, 'University of Minnesota', 0, 0, 0, 'Draw')
(53, 'Tufts University', 0, 0, 0, 'Draw')
(54, 'University of California, Davis', 0, 0, 0, 'Draw')
(55, 'Brown University', 0, 0, 0, 'Draw')
(56, 'University of Massachusetts', 0, 0, 0, 'Draw')
(57, 'Kyoto University', 0, 0, 0, 'Draw')
(58, 'Tsinghua University', 0, 0, 0, 'Draw')
(59, 'Boston University', 0, 0, 0, 'Draw')
(60, 'New York University', 0, 0, 0, 'Draw')
(61, 'Emory University', 0, 0, 0, 'Draw')
(62, 'LMU Munich', 0, 0, 0, 'Draw')
(63, 'University of Notre Dame', 0, 0, 0, 'Draw')
(64, 'University of Pittsburgh', 0, 0, 0, 'Draw')
(65, 'Case Western Reserve University', 0, 0, 0, 'Draw')
(66, 'Ohio State University', 0, 0, 0, 'Draw')
(67, 'University of Colorado Boulder', 0, 0, 0, 'Draw')
(68, 'University of Bristol', 0, 0, 0, 'Draw')
(69, 'University of California, Santa Cruz', 0, 0, 0, 'Draw')
(70, 'Yeshiva University', 0, 0, 0, 'Draw')
(71, 'University of Sydney', 0, 0, 0, 'Draw')
(72, 'University of Virginia', 0, 0, 0, 'Draw')
(73, 'University of Adelaide', 0, 0, 0, 'Draw')
(74, 'University of Southern California', 0, 0, 0, 'Draw')
(75, 'William & Mary', 0, 0, 0, 'Draw')
(76, 'Trinity College Dublin', 0, 0, 0, 'Draw')
(77, 'King’s College London', 0, 0, 0, 'Draw')
(78, 'Stony Brook University', 0, 0, 0, 'Draw')
(79, 'Korea Advanced Institute of Science and Technology (KAIST)', 0, 0, 0, 'Draw')
(80, 'University of Sussex', 0, 0, 0, 'Draw')
(81, 'The University of Queensland', 0, 0, 0, 'Draw')
(82, 'University of York', 0, 0, 0, 'Draw')
(83, 'Heidelberg University', 0, 0, 0, 'Draw')
(84, 'University of Utah', 0, 0, 0, 'Draw')
(85, 'Durham University', 0, 0, 0, 'Draw')
(86, 'London School of Economics and Political Science', 0, 0, 0, 'Draw')
(87, 'University of Manchester', 0, 0, 0, 'Draw')
(88, 'Royal Holloway, University of London', 0, 0, 0, 'Draw')
(89, 'Lund University', 0, 0, 0, 'Draw')
(90, 'University of Southampton', 0, 0, 0, 'Draw')
(91, 'University of Zurich', 0, 0, 0, 'Draw')
(92, 'Wake Forest University', 0, 0, 0, 'Draw')
(93, 'McMaster University', 0, 0, 0, 'Draw')
(94, 'University College Dublin', 0, 0, 0, 'Draw')
(95, 'George Washington University', 0, 0, 0, 'Draw')
(96, 'University of Arizona', 0, 0, 0, 'Draw')
(97, 'University of Basel', 0, 0, 0, 'Draw')
(98, 'University of Maryland, College Park', 0, 0, 0, 'Draw')
(99, 'Dartmouth College', 0, 0, 0, 'Draw')
(100, 'École Normale Supérieure de Lyon', 0, 0, 0, 'Draw')
(101, 'Technical University of Munich', 0, 0, 0, 'Draw')
(102, 'University of Helsinki', 0, 0, 0, 'Draw')
(103, 'University of St Andrews', 0, 0, 0, 'Draw')
(104, 'Rensselaer Polytechnic Institute', 0, 0, 0, 'Draw')
(105, 'Rutgers, the State University of New Jersey', 0, 0, 0, 'Draw')
(106, 'Purdue University', 0, 0, 0, 'Draw')
(107, 'National Tsing Hua University', 0, 0, 0, 'Draw')
(108, 'University of Cape Town', 0, 0, 0, 'Draw')
(109, 'Pennsylvania State University', 0, 0, 0, 'Draw')
(110, 'Seoul National University', 0, 0, 0, 'Draw')
(111, 'Hong Kong Baptist University', 0, 0, 0, 'Draw')
(112, 'Bilkent University', 0, 0, 0, 'Draw')
(113, 'Tokyo Institute of Technology', 0, 0, 0, 'Draw')
(114, 'Eindhoven University of Technology', 0, 0, 0, 'Draw')
(115, 'National Taiwan University', 0, 0, 0, 'Draw')
(116, 'University of Hawai’i at Mānoa', 0, 0, 0, 'Draw')
(117, 'University of California, Riverside', 0, 0, 0, 'Draw')
(118, 'University of Geneva', 0, 0, 0, 'Draw')
(119, 'KU Leuven', 0, 0, 0, 'Draw')
(120, 'Nanjing University', 0, 0, 0, 'Draw')
(121, 'Queen Mary University of London', 0, 0, 0, 'Draw')
(122, 'Michigan State University', 0, 0, 0, 'Draw')
(123, 'Technical University of Denmark', 0, 0, 0, 'Draw')
(124, 'Ghent University', 0, 0, 0, 'Draw')
(125, 'Lancaster University', 0, 0, 0, 'Draw')
(126, 'Leiden University', 0, 0, 0, 'Draw')
(127, 'University of Alberta', 0, 0, 0, 'Draw')
(128, 'University of Glasgow', 0, 0, 0, 'Draw')
(129, 'Stockholm University', 0, 0, 0, 'Draw')
(130, 'Osaka University', 0, 0, 0, 'Draw')
(131, 'University of Victoria', 0, 0, 0, 'Draw')
(132, 'Tohoku University', 0, 0, 0, 'Draw')
(133, 'University of Freiburg', 0, 0, 0, 'Draw')
(134, 'University of Iowa', 0, 0, 0, 'Draw')
(135, 'University of Bergen', 0, 0, 0, 'Draw')
(136, 'University of Lausanne', 0, 0, 0, 'Draw')
(137, 'University of Sheffield', 0, 0, 0, 'Draw')
(138, 'University of Montreal', 0, 0, 0, 'Draw')
(139, 'VU University Amsterdam', 0, 0, 0, 'Draw')
(140, 'Pierre and Marie Curie University', 0, 0, 0, 'Draw')
(141, 'University of Dundee', 0, 0, 0, 'Draw')
(142, 'University of Barcelona', 0, 0, 0, 'Draw')
(143, 'Utrecht University', 0, 0, 0, 'Draw')
(144, 'Wageningen University and Research Center', 0, 0, 0, 'Draw')
(145, 'University of Auckland', 0, 0, 0, 'Draw')
(146, 'University of Birmingham', 0, 0, 0, 'Draw')
(147, 'Alexandria University', 0, 0, 0, 'Draw')
(148, 'Uppsala University', 0, 0, 0, 'Draw')
(149, 'Hong Kong Polytechnic University', 0, 0, 0, 'Draw')
(150, 'University of Aberdeen', 0, 0, 0, 'Draw')
(151, 'Delft University of Technology', 0, 0, 0, 'Draw')
(152, 'Birkbeck, University of London', 0, 0, 0, 'Draw')
(153, 'Newcastle University', 0, 0, 0, 'Draw')
(154, 'University of New South Wales', 0, 0, 0, 'Draw')
(155, 'Pompeu Fabra University', 0, 0, 0, 'Draw')
(156, 'Indiana University', 0, 0, 0, 'Draw')
(157, 'Iowa State University', 0, 0, 0, 'Draw')
(158, 'Georgia Health Sciences University', 0, 0, 0, 'Draw')
(159, 'Erasmus University Rotterdam', 0, 0, 0, 'Draw')
(160, 'University of Delaware', 0, 0, 0, 'Draw')
(161, 'Arizona State University', 0, 0, 0, 'Draw')
(162, 'Boston College', 0, 0, 0, 'Draw')
(163, 'National Sun Yat-Sen University', 0, 0, 0, 'Draw')
(164, 'Georgetown University', 0, 0, 0, 'Draw')
(165, 'University of Amsterdam', 0, 0, 0, 'Draw')
(166, 'University of Liverpool', 0, 0, 0, 'Draw')
(167, 'Aarhus University', 0, 0, 0, 'Draw')
(168, 'University of Leeds', 0, 0, 0, 'Draw')
(169, 'University of Würzburg', 0, 0, 0, 'Draw')
(170, 'University of Groningen', 0, 0, 0, 'Draw')
(171, 'Sun Yat-sen University', 0, 0, 0, 'Draw')
(172, 'Goethe University Frankfurt', 0, 0, 0, 'Draw')
(173, 'Bielefeld University', 0, 0, 0, 'Draw')
(174, 'Nanyang Technological University', 0, 0, 0, 'Draw')
(175, 'University of East Anglia', 0, 0, 0, 'Draw')
(176, 'University of Nottingham', 0, 0, 0, 'Draw')
(177, 'University of Copenhagen', 0, 0, 0, 'Draw')
(178, 'Humboldt University of Berlin', 0, 0, 0, 'Draw')
(179, 'Monash University', 0, 0, 0, 'Draw')
(180, 'University of Bonn', 0, 0, 0, 'Draw')
(181, 'National Chiao Tung University', 0, 0, 0, 'Draw')
(182, 'RWTH Aachen University', 0, 0, 0, 'Draw')
(183, 'Middle East Technical University', 0, 0, 0, 'Draw')
(184, 'University of Exeter', 0, 0, 0, 'Draw')
(185, 'University of Twente', 0, 0, 0, 'Draw')
(186, 'University of Konstanz', 0, 0, 0, 'Draw')
(187, 'Karlsruhe Institute of Technology', 0, 0, 0, 'Draw')
(188, 'University of Innsbruck', 0, 0, 0, 'Draw')
(189, 'University of Tübingen', 0, 0, 0, 'Draw')
(190, 'Drexel University', 0, 0, 0, 'Draw')
(191, 'University of Cincinnati', 0, 0, 0, 'Draw')
(192, 'Yonsei University', 0, 0, 0, 'Draw')
(193, 'Dalhousie University', 0, 0, 0, 'Draw')
(194, 'KTH Royal Institute of Technology', 0, 0, 0, 'Draw')
(195, 'University of Vienna', 0, 0, 0, 'Draw')
(196, 'Kent State University', 0, 0, 0, 'Draw')
(197, 'University of Illinois at Chicago', 0, 0, 0, 'Draw')
(198, 'Zhejiang University', 0, 0, 0, 'Draw')
(199, 'Simon Fraser University', 0, 0, 0, 'Draw')
(200, 'Swedish University of Agricultural Sciences', 0, 0, 0, 'Draw')
(201, 'University of Wisconsin-Madison', 0, 0, 0, 'Draw')
(202, 'University of Texas at Austin', 0, 0, 0, 'Draw')
(203, 'University of Rochester', 0, 0, 0, 'Draw')
(204, 'University of Bern', 0, 0, 0, 'Draw')
(205, 'Hebrew University of Jerusalem', 0, 0, 0, 'Draw')
(206, 'University of Florida', 0, 0, 0, 'Draw')
(207, 'Brandeis University', 0, 0, 0, 'Draw')
(208, 'Chinese University of Hong Kong', 0, 0, 0, 'Draw')
(209, 'Free University of Berlin', 0, 0, 0, 'Draw')
(210, 'University of Warwick', 0, 0, 0, 'Draw')
(211, 'Radboud University Nijmegen', 0, 0, 0, 'Draw')
(212, 'Medical University of South Carolina', 0, 0, 0, 'Draw')
(213, 'Texas A&M University', 0, 0, 0, 'Draw')
(214, 'University of Reading', 0, 0, 0, 'Draw')
(215, 'Tel Aviv University', 0, 0, 0, 'Draw')
(216, 'Paris Diderot University – Paris 7', 0, 0, 0, 'Draw')
(217, 'Université Catholique de Louvain', 0, 0, 0, 'Draw')
(218, 'University of Miami', 0, 0, 0, 'Draw')
(219, 'Queen’s University', 0, 0, 0, 'Draw')
(220, 'University of São Paulo', 0, 0, 0, 'Draw')
(221, 'University of Oslo', 0, 0, 0, 'Draw')
(222, 'University of Ottawa', 0, 0, 0, 'Draw')
(223, 'University of Western Australia', 0, 0, 0, 'Draw')
(224, 'City University of Hong Kong', 0, 0, 0, 'Draw')
(225, 'Maastricht University', 0, 0, 0, 'Draw')
(226, 'University of Leicester', 0, 0, 0, 'Draw')
(227, 'Autonomous University of Barcelona', 0, 0, 0, 'Draw')
(228, 'Cardiff University', 0, 0, 0, 'Draw')
(229, 'Colorado School of Mines', 0, 0, 0, 'Draw')
(230, 'Nagoya University', 0, 0, 0, 'Draw')
(231, 'Northeastern University', 0, 0, 0, 'Draw')
(232, 'Technion Israel Institute of Technology', 0, 0, 0, 'Draw')
(233, 'Tulane University', 0, 0, 0, 'Draw')
(234, 'Ulm University', 0, 0, 0, 'Draw')
(235, 'Umeå University', 0, 0, 0, 'Draw')
(236, 'University at Buffalo', 0, 0, 0, 'Draw')
(237, 'University of Essex', 0, 0, 0, 'Draw')
(238, 'University of Georgia', 0, 0, 0, 'Draw')
(239, 'University of Gothenburg', 0, 0, 0, 'Draw')
(240, 'University of Medicine and Dentistry of New Jersey', 0, 0, 0, 'Draw')
(241, 'University of Otago', 0, 0, 0, 'Draw')
(242, 'University of South Carolina', 0, 0, 0, 'Draw')
(243, 'University of Strasbourg', 0, 0, 0, 'Draw')
(244, 'University of Waterloo', 0, 0, 0, 'Draw')
(245, 'University of Western Ontario', 0, 0, 0, 'Draw')
(246, 'Université Libre de Bruxelles', 0, 0, 0, 'Draw')
(247, 'Carleton University', 0, 0, 0, 'Draw')
(248, 'Chalmers University of Technology', 0, 0, 0, 'Draw')
(249, 'Colorado State University', 0, 0, 0, 'Draw')
(250, 'Creighton University', 0, 0, 0, 'Draw')
(251, 'Fudan University', 0, 0, 0, 'Draw')
(252, 'Korea University', 0, 0, 0, 'Draw')
(253, 'Macquarie University', 0, 0, 0, 'Draw')
(254, 'State University of New York Albany', 0, 0, 0, 'Draw')
(255, 'Tokyo Metropolitan University', 0, 0, 0, 'Draw')
(256, 'University of Bologna', 0, 0, 0, 'Draw')
(257, 'University of Calgary', 0, 0, 0, 'Draw')
(258, 'University of Hamburg', 0, 0, 0, 'Draw')
(259, 'University of Milan', 0, 0, 0, 'Draw')
(260, 'University of Milan-Bicocca', 0, 0, 0, 'Draw')
(261, 'University of Missouri', 0, 0, 0, 'Draw')
(262, 'University of Padua', 0, 0, 0, 'Draw')
(263, 'University of Trieste', 0, 0, 0, 'Draw')
(264, 'Bangor University', 0, 0, 0, 'Draw')
(265, 'Brunel University London', 0, 0, 0, 'Draw')
(266, 'Johannes Kepler University of Linz', 0, 0, 0, 'Draw')
(267, 'Kyushu University', 0, 0, 0, 'Draw')
(268, 'Norwegian University of Science and Technology', 0, 0, 0, 'Draw')
(269, 'Queen’s University Belfast', 0, 0, 0, 'Draw')
(270, 'Ruhr University Bochum', 0, 0, 0, 'Draw')
(271, 'Stellenbosch University', 0, 0, 0, 'Draw')
(272, 'Tilburg University', 0, 0, 0, 'Draw')
(273, 'TU Dresden', 0, 0, 0, 'Draw')
(274, 'University of Bath', 0, 0, 0, 'Draw')
(275, 'University of Graz', 0, 0, 0, 'Draw')
(276, 'University of Kiel', 0, 0, 0, 'Draw')
(277, 'University of Southern Denmark', 0, 0, 0, 'Draw')
(278, 'University of Texas at Dallas', 0, 0, 0, 'Draw')
(279, 'University of the Witwatersrand', 0, 0, 0, 'Draw')
(280, 'University of Tsukuba', 0, 0, 0, 'Draw')
(281, 'University of Wollongong', 0, 0, 0, 'Draw')
(282, 'Victoria University of Wellington', 0, 0, 0, 'Draw')
(283, 'Virginia Polytechnic Institute and State University', 0, 0, 0, 'Draw')
(284, 'Wayne State University', 0, 0, 0, 'Draw')
(285, 'Aberystwyth University', 0, 0, 0, 'Draw')
(286, 'Autonomous University of Madrid', 0, 0, 0, 'Draw')
(287, 'Hokkaido University', 0, 0, 0, 'Draw')
(288, 'Istanbul Technical University', 0, 0, 0, 'Draw')
(289, 'Lomonosov Moscow State University', 0, 0, 0, 'Draw')
(290, 'Montpellier University', 0, 0, 0, 'Draw')
(291, 'Queensland University of Technology', 0, 0, 0, 'Draw')
(292, 'State University of Campinas', 0, 0, 0, 'Draw')
(293, 'Technical University of Darmstadt', 0, 0, 0, 'Draw')
(294, 'Tokyo Medical and Dental University (TMDU)', 0, 0, 0, 'Draw')
(295, 'UiT The Arctic University of Norway', 0, 0, 0, 'Draw')
(296, 'University of Antwerp', 0, 0, 0, 'Draw')
(297, 'University of Crete', 0, 0, 0, 'Draw')
(298, 'University of Guelph', 0, 0, 0, 'Draw')
(299, 'University of Iceland', 0, 0, 0, 'Draw')
(300, 'University of Kansas', 0, 0, 0, 'Draw')
(301, 'University of Kentucky', 0, 0, 0, 'Draw')
(302, 'University of Münster', 0, 0, 0, 'Draw')
(303, 'University of Newcastle', 0, 0, 0, 'Draw')
(304, 'University of Texas at San Antonio', 0, 0, 0, 'Draw')
(305, 'University of Trento', 0, 0, 0, 'Draw')
(306, 'York University', 0, 0, 0, 'Draw')
(307, 'Aalborg University', 0, 0, 0, 'Draw')
(308, 'Aalto University', 0, 0, 0, 'Draw')
(309, 'Bar-Ilan University', 0, 0, 0, 'Draw')
(310, 'Binghamton University, State University of New York', 0, 0, 0, 'Draw')
(311, 'Boğaziçi University', 0, 0, 0, 'Draw')
(312, 'Charles Darwin University', 0, 0, 0, 'Draw')
(313, 'Charles University in Prague', 0, 0, 0, 'Draw')
(314, 'George Mason University', 0, 0, 0, 'Draw')
(315, 'Indian Institute of Technology Bombay', 0, 0, 0, 'Draw')
(316, 'Jagiellonian University', 0, 0, 0, 'Draw')
(317, 'Keele University', 0, 0, 0, 'Draw')
(318, 'Keio University', 0, 0, 0, 'Draw')
(319, 'Lehigh University', 0, 0, 0, 'Draw')
(320, 'Linköping University', 0, 0, 0, 'Draw')
(321, 'National Taiwan University of Science and Technology (Taiwan Tech)', 0, 0, 0, 'Draw')
(322, 'Plymouth University', 0, 0, 0, 'Draw')
(323, 'Polytechnic University of Milan', 0, 0, 0, 'Draw')
(324, 'Sapienza University of Rome', 0, 0, 0, 'Draw')
(325, 'Shanghai Jiao Tong University', 0, 0, 0, 'Draw')
(326, 'Sharif University of Technology', 0, 0, 0, 'Draw')
(327, 'Sungkyunkwan University (SKKU)', 0, 0, 0, 'Draw')
(328, 'University College Cork', 0, 0, 0, 'Draw')
(329, 'University of Aveiro', 0, 0, 0, 'Draw')
(330, 'University of Canterbury', 0, 0, 0, 'Draw')
(331, 'University of Eastern Finland', 0, 0, 0, 'Draw')
(332, 'University of Ferrara', 0, 0, 0, 'Draw')
(333, 'University of Hertfordshire', 0, 0, 0, 'Draw')
(334, 'University of Houston', 0, 0, 0, 'Draw')
(335, 'University of Hull', 0, 0, 0, 'Draw')
(336, 'University of Liège', 0, 0, 0, 'Draw')
(337, 'University of Manitoba', 0, 0, 0, 'Draw')
(338, 'University of Maryland, Baltimore County', 0, 0, 0, 'Draw')
(339, 'University of Modena and Reggio Emilia', 0, 0, 0, 'Draw')
(340, 'University of Oklahoma', 0, 0, 0, 'Draw')
(341, 'University of Pisa', 0, 0, 0, 'Draw')
(342, 'University of Porto', 0, 0, 0, 'Draw')
(343, 'University of South Florida', 0, 0, 0, 'Draw')
(344, 'University of Stirling', 0, 0, 0, 'Draw')
(345, 'University of Surrey', 0, 0, 0, 'Draw')
(346, 'University of Tampere', 0, 0, 0, 'Draw')
(347, 'University of Tasmania', 0, 0, 0, 'Draw')
(348, 'University of Valencia', 0, 0, 0, 'Draw')
(349, 'University of Waikato', 0, 0, 0, 'Draw')
(350, 'University of Warsaw', 0, 0, 0, 'Draw')
(351, 'Vienna University of Technology', 0, 0, 0, 'Draw')
(352, 'Vrije Universiteit Brussel', 0, 0, 0, 'Draw')
(353, 'Washington State University', 0, 0, 0, 'Draw')
(354, 'Aston University', 0, 0, 0, 'Draw')
(355, 'Auburn University', 0, 0, 0, 'Draw')
(356, 'Clemson University', 0, 0, 0, 'Draw')
(357, 'Curtin University', 0, 0, 0, 'Draw')
(358, 'Deakin University', 0, 0, 0, 'Draw')
(359, 'Flinders University', 0, 0, 0, 'Draw')
(360, 'Georgia State University', 0, 0, 0, 'Draw')
(361, 'Griffith University', 0, 0, 0, 'Draw')
(362, 'Harbin Institute of Technology', 0, 0, 0, 'Draw')
(363, 'Heriot-Watt University', 0, 0, 0, 'Draw')
(364, 'Hiroshima University', 0, 0, 0, 'Draw')
(365, 'Kansas State University', 0, 0, 0, 'Draw')
(366, 'Kobe University', 0, 0, 0, 'Draw')
(367, 'Kyung Hee University', 0, 0, 0, 'Draw')
(368, 'La Trobe University', 0, 0, 0, 'Draw')
(369, 'Leibniz University of Hanover', 0, 0, 0, 'Draw')
(370, 'Liverpool John Moores University', 0, 0, 0, 'Draw')
(371, 'Loughborough University', 0, 0, 0, 'Draw')
(372, 'Mahidol University', 0, 0, 0, 'Draw')
(373, 'Massey University', 0, 0, 0, 'Draw')
(374, 'Michigan Technological University', 0, 0, 0, 'Draw')
(375, 'National Central University', 0, 0, 0, 'Draw')
(376, 'National Taiwan Ocean University', 0, 0, 0, 'Draw')
(377, 'National University of Ireland, Galway', 0, 0, 0, 'Draw')
(378, 'National University of Ireland, Maynooth', 0, 0, 0, 'Draw')
(379, 'New Jersey Institute of Technology', 0, 0, 0, 'Draw')
(380, 'New University of Lisbon', 0, 0, 0, 'Draw')
(381, 'Old Dominion University', 0, 0, 0, 'Draw')
(382, 'Polytechnic University of Catalonia', 0, 0, 0, 'Draw')
(383, 'Polytechnic University of Turin', 0, 0, 0, 'Draw')
(384, 'Polytechnic University of Valencia', 0, 0, 0, 'Draw')
(385, 'Pontifical Catholic University of Chile', 0, 0, 0, 'Draw')
(386, 'Saint Petersburg State University', 0, 0, 0, 'Draw')

In [ ]:
#Show the structure

# Connect to you

Structure of table 'rankings':
Column Name: id_school, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: school_name, Data Type: TEXT, Not Null: 0, Default Value: None
Column Name: td_country, Data Type: TEXT, Not Null: 0, Default Value: None
Column Name: td_world_rank, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: shanghai_world_rank, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: cwur_world_rank, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: td_num_students, Data Type: FLOAT, Not Null: 0, Default Value: None
Column Name: td_international_students, Data Type: FLOAT, Not Null: 0, Default Value: None
Column Name: s_award, Data Type: FLOAT, Not Null: 0, Default Value: None
Column Name: cw_alumni_employment, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: cw_publications, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: cw_influence, Data Type: INTEGER, Not Null: 0, Default Value: None
Column Name: year, Data Type: INTEGER, Not Null: 0, Default Value: None

In [ ]:


# Connect to your database
conn = sqlite3.connect('Tarea.db')
c = conn.cursor()

#Universidades que más veces aparecieron en el top ten de shangai
c.execute('''
WITH top_ten AS (
    SELECT DISTINCT
        rk.id_school,
        rk.school_name,
        CASE WHEN LOWER(rk.td_world_rank) < '10' THEN 1 ELSE 0 END AS td_top_ten,
        CASE WHEN LOWER(rk.shanghai_world_rank) < '10' THEN 1 ELSE 0 END AS sh_top_ten,
        CASE WHEN LOWER(rk.cwur_world_rank) < '10' THEN 1 ELSE 0 END AS cwur_top_ten,
        rk.year
    FROM rankings rk
    WHERE rk.year >= 2012
),

bq AS (
    SELECT DISTINCT
        id_school,
        school_name,
        SUM(td_top_ten) AS td_top_ten_times,
        SUM(sh_top_ten) AS sh_top_ten_times,
        SUM(cwur_top_ten) AS cwur_top_ten_times

    FROM top_ten
    GROUP BY id_school, school_name
    ORDER BY id_school ASC
    )

SELECT DISTINCT
id_school,
school_name,
sh_top_ten_times
FROM bq
ORDER BY sh_top_ten_times DESC

    ''')

# Fetch all results
results = c.fetchall()

# Display the results
for row in results:
    print(f"ID: {row[0]}, School Name: {row[1]}, Shanghai Top Ten Times: {row[2]}")

# Close the connection

In [ ]:
#Universidades que más veces aparecieron en el top ten de tames data
c.execute('''
WITH top_ten AS (
    SELECT DISTINCT
        rk.id_school,
        rk.school_name,
        CASE WHEN LOWER(rk.td_world_rank) < '10' THEN 1 ELSE 0 END AS td_top_ten,
        CASE WHEN LOWER(rk.shanghai_world_rank) < '10' THEN 1 ELSE 0 END AS sh_top_ten,
        CASE WHEN LOWER(rk.cwur_world_rank) < '10' THEN 1 ELSE 0 END AS cwur_top_ten,
        rk.year
    FROM rankings rk
    WHERE rk.year >= 2011
),

bq AS (
    SELECT DISTINCT
        id_school,
        school_name,
        SUM(td_top_ten) AS td_top_ten_times,
        SUM(sh_top_ten) AS sh_top_ten_times,
        SUM(cwur_top_ten) AS cwur_top_ten_times

    FROM top_ten
    GROUP BY id_school, school_name
    ORDER BY id_school ASC
    )

SELECT DISTINCT
id_school,
school_name,
td_top_ten_times
FROM bq
ORDER BY td_top_ten_times DESC

    ''')

In [ ]:
#Universidades que más veces aparecieron en el top ten de tames data
c.execute('''
WITH top_ten AS (
    SELECT DISTINCT
        rk.id_school,
        rk.school_name,
        CASE WHEN LOWER(rk.td_world_rank) < '10' THEN 1 ELSE 0 END AS td_top_ten,
        CASE WHEN LOWER(rk.shanghai_world_rank) < '10' THEN 1 ELSE 0 END AS sh_top_ten,
        CASE WHEN LOWER(rk.cwur_world_rank) < '10' THEN 1 ELSE 0 END AS cwur_top_ten,
        rk.year
    FROM rankings rk
    WHERE rk.year >= 2011
),

bq AS (
    SELECT DISTINCT
        id_school,
        school_name,
        SUM(td_top_ten) AS td_top_ten_times,
        SUM(sh_top_ten) AS sh_top_ten_times,
        SUM(cwur_top_ten) AS cwur_top_ten_times

    FROM top_ten
    GROUP BY id_school, school_name
    ORDER BY id_school ASC
    )

SELECT DISTINCT
id_school,
school_name,
cwur_top_ten_times
FROM bq
ORDER BY cwur_top_ten_times DESC

    ''')